import json

scene_data = [
  {
    "__type__": "cc.SceneAsset",
    "_name": "",
    "_objFlags": 0,
    "_native": "",
    "scene": { "__id__": 1 }
  },
  {
    "__type__": "cc.Scene",
    "_name": "MainScene",
    "_objFlags": 0,
    "_parent": None,
    "_children": [ { "__id__": 2 } ],
    "_active": True,
    "_components": [],
    "_prefab": None,
    "_opacity": 255,
    "_color": { "__type__": "cc.Color", "r": 255, "g": 255, "b": 255, "a": 255 },
    "_contentSize": { "__type__": "cc.Size", "width": 0, "height": 0 },
    "_anchorPoint": { "__type__": "cc.Vec2", "x": 0, "y": 0 },
    "_scale": { "__type__": "cc.Vec3", "x": 1, "y": 1, "z": 1 },
    "_is3DNode": True,
    "groupIndex": 0,
    "autoReleaseAssets": False,
    "_id": "scene-id"
  },
  {
    "__type__": "cc.Node",
    "_name": "Canvas",
    "_objFlags": 0,
    "_parent": { "__id__": 1 },
    "_children": [ { "__id__": 3 } ],
    "_active": True,
    "_components": [ { "__id__": 4 }, { "__id__": 5 } ],
    "_prefab": None,
    "_opacity": 255,
    "_color": { "__type__": "cc.Color", "r": 255, "g": 255, "b": 255, "a": 255 },
    "_contentSize": { "__type__": "cc.Size", "width": 960, "height": 640 },
    "_anchorPoint": { "__type__": "cc.Vec2", "x": 0.5, "y": 0.5 },
    "_position": { "__type__": "cc.Vec3", "x": 480, "y": 320, "z": 0 },
    "_scale": { "__type__": "cc.Vec3", "x": 1, "y": 1, "z": 1 },
    "_is3DNode": False,
    "groupIndex": 0,
    "_id": "canvas-id"
  },
  {
    "__type__": "cc.Node",
    "_name": "Main Camera",
    "_objFlags": 0,
    "_parent": { "__id__": 2 },
    "_children": [],
    "_active": True,
    "_components": [ { "__id__": 6 } ],
    "_prefab": None,
    "_opacity": 255,
    "_color": { "__type__": "cc.Color", "r": 255, "g": 255, "b": 255, "a": 255 },
    "_contentSize": { "__type__": "cc.Size", "width": 0, "height": 0 },
    "_anchorPoint": { "__type__": "cc.Vec2", "x": 0.5, "y": 0.5 },
    "_position": { "__type__": "cc.Vec3", "x": 0, "y": 0, "z": 0 },
    "_scale": { "__type__": "cc.Vec3", "x": 1, "y": 1, "z": 1 },
    "_is3DNode": False,
    "groupIndex": 0,
    "_id": "camera-id"
  },
  {
    "__type__": "cc.Canvas",
    "_name": "",
    "_objFlags": 0,
    "node": { "__id__": 2 },
    "_enabled": True,
    "_designResolution": { "__type__": "cc.Size", "width": 960, "height": 640 },
    "_fitWidth": False,
    "_fitHeight": True,
    "_id": "canvas-comp-id"
  },
  {
    "__type__": "cc.Widget",
    "_name": "",
    "_objFlags": 0,
    "node": { "__id__": 2 },
    "_enabled": True,
    "alignMode": 1,
    "_target": None,
    "_alignFlags": 45,
    "_left": 0,
    "_right": 0,
    "_top": 0,
    "_bottom": 0,
    "_verticalCenter": 0,
    "_horizontalCenter": 0,
    "_isAbsLeft": True,
    "_isAbsRight": True,
    "_isAbsTop": True,
    "_isAbsBottom": True,
    "_isAbsHorizontalCenter": True,
    "_isAbsVerticalCenter": True,
    "_originalWidth": 0,
    "_originalHeight": 0
  },
  {
    "__type__": "cc.Camera",
    "_name": "",
    "_objFlags": 0,
    "node": { "__id__": 3 },
    "_enabled": True,
    "_cullingMask": 4294967295,
    "_clearFlags": 7,
    "_backgroundColor": { "__type__": "cc.Color", "r": 0, "g": 0, "b": 0, "a": 255 },
    "_depth": -1,
    "_zoomRatio": 1,
    "_targetTexture": None,
    "_fov": 60,
    "_orthoSize": 320,
    "_nearClip": 1,
    "_farClip": 4096,
    "_ortho": True,
    "_rect": { "__type__": "cc.Rect", "x": 0, "y": 0, "width": 1, "height": 1 },
    "_renderStages": 1,
    "_alignWithScreen": True,
    "_id": "camera-comp-id"
  }
]

with open('/Users/bytedance/Documents/cocos_cli/vampire_demo/assets/scenes/MainScene.fire', 'w') as f:
    json.dump(scene_data, f, indent=2)

print("MainScene.fire generated successfully.")
